// <auto-generated />
namespace urednistvo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kokos24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kokos24));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291236512_kokos24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
